version: "3.8"

networks:
  phx-network:

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - phx-network
    deploy:
      mode: replicated
      replicas: 1

volumes:
  mongodb_data: